#!/bin/bash

echo "=================================================="
echo "🚀 Progo-AI RAG Project - Quick Start"
echo "=================================================="
echo ""
echo "You have two options:"
echo ""
echo "OPTION 1: Ask a single question"
echo "  ./venv/bin/python3 query_interface.py \"What is Order Push API?\""
echo ""
echo "OPTION 2: Interactive mode (multiple questions)"
echo "  ./venv/bin/python3 query_interface.py"
echo ""
echo "=================================================="
echo ""
echo "Example questions to try:"
echo "  • What is Order Push API?"
echo "  • What parameters does push-order need?"
echo "  • How do I authenticate with the API?"
echo "  • What warehouses are available?"
echo "  • Show me an example request"
echo ""
echo "=================================================="
